# Generated by Django 5.0.7 on 2025-10-22 00:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=60, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Cor')),
                ('odometer', models.PositiveIntegerField(default=0, verbose_name='Quilometragem')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço por dia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo para locação')),
            ],
            options={
                'ordering': ['brand', 'model', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('document', models.CharField(max_length=20, unique=True, verbose_name='Documento (CPF/ID)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('agreed_daily_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('odometer_start', models.PositiveIntegerField(blank=True, null=True)),
                ('odometer_end', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=120)),
                ('return_location', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('reserved', 'Reservada'), ('ongoing', 'Em curso'), ('finished', 'Finalizada'), ('canceled', 'Cancelada')], default='reserved', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rental.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rental.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='rental_start_before_end'),
        ),
    ]
